# This is a basic workflow to help you get started with Actions

name: Angular 13 [Preview]
on:
  push:
    branches: [ "angular-13/preview" ]
  pull_request:
    branches: [ "angular-13/preview" ]

env:
  IS_PREVIEW: true

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install project dependencies
      - run: npm install

      # Build the library
      - run: npm run build:lib

      # Publish the library
      - run: npm run publish


