# This is a basic workflow to help you get started with Actions

name: Angular 13 [Preview]
on:
  push:
    branches: [ "angular-13/preview" ]
  pull_request:
    branches: [ "angular-13/preview" ]

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install project dependencies
      - run: npm install

      # Build the library
      - run: node ./node_modules/@angular/cli/bin/ng build ngx-map-quest -c production

      # Generate .npmrc file
      - run: echo "registry=https://$NPM_REGISTRY/" >> "./dist/ngx-map-quest/.npmrc"
      - run: echo "always-auth=true" >> "./dist/ngx-map-quest/.npmrc"
      - run: echo "//$NPM_REGISTRY/:_authToken=$NPM_ACCESS_TOKEN"

      # Publish the library
      - run: node ./node_modules/@angular/cli/bin/ng publish ./dist/ngx-map-quest


